apiVersion: v1
kind: Service
metadata:
  name: face-service
  labels:
    app: cbroker
spec:
  type: NodePort
  ports:
  - nodePort: 32364
    port: 1883
    protocol: TCP
    targetPort: 1883
  selector:
    app: cbroker
