apiVersion: v1
kind: Service
metadata:
  name: face-service
  labels:
    run: mybroker
spec:
  type: NodePort
  ports:
  - port: 1883
    protocol: TCP
    targetPort: 1883
  selector:
    app: mybroker
