apiVersion: apps/v1
kind: Deployment
metadata:
  name: mylogger-deployment
spec:
  selector:
    matchLabels:
      app: mybroker
  replicas: 1 # tells deployment to run 1 pods matching the template
  template:
    metadata:
      labels:
        app: mybroker
    spec:
      containers:
      - name: mylogger
        image: ncpaxton01/mylogger:latest
      - name: forwarder
        image: ncpaxton01/forwarder:latest
      - name: capture
        image: ncpaxton01/cappub:latest
        securityContext: 
          privileged: true
        volumeMounts:
        - mountPath: /dev/video0
          name: dev-video0
      volumes:
      - name: dev-video0
        hostPath:
          path: /dev/video0
       
